POST http://localhost:5000/api/login
Content-Type: application/json

{
  "email": "johndoe@gmail.com",
  "password": "123456"
}

###
POST http://localhost:5000/api/register
Content-Type: application/json

{
  "email": "johndoe@gmail.com",
  "name": "John Doe",
  "password": "123456"
}

###
GET http://localhost:5000/api/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY2Njk2MzUzNiwianRpIjoiZWI0NDNkYjgtZjA0NC00ZGZhLWFlZTYtMWRhZjMwOTQzNzYxIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6MSwibmJmIjoxNjY2OTYzNTM2LCJleHAiOjE2NjY5NjQ0MzZ9.L90gUFFTb-z6EMbrlSvlw0Y9u9Xg4hpCmLnj-urGG4I


###
GET http://localhost:5000/api/todos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY2Njk2MzUzNiwianRpIjoiZWI0NDNkYjgtZjA0NC00ZGZhLWFlZTYtMWRhZjMwOTQzNzYxIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6MSwibmJmIjoxNjY2OTYzNTM2LCJleHAiOjE2NjY5NjQ0MzZ9.L90gUFFTb-z6EMbrlSvlw0Y9u9Xg4hpCmLnj-urGG4I


###
POST http://localhost:5000/api/todos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY2Njk2MzUzNiwianRpIjoiZWI0NDNkYjgtZjA0NC00ZGZhLWFlZTYtMWRhZjMwOTQzNzYxIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6MSwibmJmIjoxNjY2OTYzNTM2LCJleHAiOjE2NjY5NjQ0MzZ9.L90gUFFTb-z6EMbrlSvlw0Y9u9Xg4hpCmLnj-urGG4I
Content-Type: application/json

{
  "title": "CIT TODO API",
  "description": "This is an api for CIT",
  "due_date": "2022-10-27"
}

###
PUT http://localhost:5000/api/todos/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY2Njk2MzUzNiwianRpIjoiZWI0NDNkYjgtZjA0NC00ZGZhLWFlZTYtMWRhZjMwOTQzNzYxIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6MSwibmJmIjoxNjY2OTYzNTM2LCJleHAiOjE2NjY5NjQ0MzZ9.L90gUFFTb-z6EMbrlSvlw0Y9u9Xg4hpCmLnj-urGG4I

{
  "complete": false,
  "description": "This is an api for CIT updated description"
}

###
DELETE http://localhost:5000/api/todos/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY2Njk2MzUzNiwianRpIjoiZWI0NDNkYjgtZjA0NC00ZGZhLWFlZTYtMWRhZjMwOTQzNzYxIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6MSwibmJmIjoxNjY2OTYzNTM2LCJleHAiOjE2NjY5NjQ0MzZ9.L90gUFFTb-z6EMbrlSvlw0Y9u9Xg4hpCmLnj-urGG4I
